In [ ]:
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
a_list+b_list #dopisuje na końcu listy znowu 1,2,3,4,5
n_array+n_array #dodaje do siebie wektory (1+1, 2+2, 3+3 itd.)

array([ 2,  4,  6,  8, 10])

In [ ]:
a_list[5] #0 - 1; 2 - 2... 5 - [1,2,3]

[1, 2, 3]

In [ ]:
a_list.append(100) #dodaje na końcu listy
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [ ]:
k_krotka[5] #tak samo jak a_list[5]

[1, 2, 3]

In [ ]:
k_krotka.append(100) #do krotki nie mozna dodawac, tzn nie tak prosto

AttributeError: ignored

In [ ]:
np.array(b_list)+np.array(b_list) #np - numpy, zreszta ten przyklad juz byl

array([ 2,  4,  6,  8, 10])

In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"} #klucz:wartość

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"] #dla klucza Zosia jest wartość 22

22

In [ ]:
for elementy in studenci_slownik: #klucze
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys(): #klucze
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [ ]:
for elementy in studenci_slownik.items(): #krotki - pary klucz:wartość 
    print(elementy)

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')


In [ ]:
for elementy in studenci_slownik.values(): #wartości 
    print(elementy)

123
3
5
22
[2, 21]
Krotka


In [ ]:
studenci_slownik["Cuthulu"]= -1000000 #dodano do slownika

In [ ]:
studenci_slownik #slownik zachowuje to w kolejnosci alfabetycznej

{(1, 2): 'Krotka',
 123: 123,
 'Cuthulu': -1000000,
 'Frankek': 5,
 'Igor': 3,
 'Julia': [2, 21],
 'Zosia': 22}

In [ ]:
automatyczna_lista  =[liczba**2 for liczba in range(100) if liczba%4==0] #do kwadratu wszystkie liczby z zakresu 0-100 jeżeli te bazowe liczby są podzielne przez 4
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik) #slownik z kluczy z starego slownika 

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [ ]:
a.add("Franek")
print(a)

{'Franek', 1, 2, 3}


In [ ]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia.ile_mispow()

4

In [ ]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 


```
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"
```


 

In [ ]:
class NumerTelefonu():
  slownik_kierunkowe = {"Kraków":12, "Krosno":13, "Tarnów":14, "Tarnobrzeg":15, "Przemyśl":16, "Rzeszów":17, "Nowy Sącz":18,
                       "Warszawa":22, "Ciechanów":23, "Płock":24, "Siedlce":25, "Ostrołęka":29, "Katowice":32, "Bielsko-Biała":33,
                       "Częstochowa":34, "Kielce":41, "Łódź":42, "Sieradz":43, "Piotrków Trybunalski":44, "Skierniewice": 46, "Radom":48,
                       "Bydgoszcz":52, "Włocławek":54, "Elbląg":55, "Toruń":56, "Gdańsk":58, "Słupsk":59, "Poznań":61, "Kalisz":62,
                       "Konin":63, "Leszno":65, "Piła":67, "Zielona Góra":68, "Wrocław":71, "Wałbrzych":74, "Jelenia Góra":75, "Legnica":76,
                       "Opole":77, "Lublin":81, "Chełm":82, "Bielsko-Biała":83, "Zamość":84, "Białystok":85, "Łomża":86, "Suwałki":87,
                       "Olsztyn":89, "Szczecin":91, "Koszalin":94, "Gorzów Wielkopolski":95} #klucz:wartość

  slownik_literuj = {'1': "jeden", '2': "dwa", '3': "trzy", '4': "cztery", '5': "pięć", '6': "sześć",
                    '7': "siedem", '8': "osiem", '9': "dziewięć", '0': "zero"} #klucz:wartość

  def __init__(self, podany_numer): #self musi być zawsze, podany_numer - must have do wpisania (dlatego, że jest w __init__)
    if len(podany_numer) == 9 and podany_numer.isdigit(): #stacjonarny i komórkowy mają po 9 cyfr oraz sprawdzam, czy są to cyfry
      self.numer = podany_numer #self. bo do samego siebie w tej klasie będzie sie odnosiło
      print("Podano poprawny numer: {}".format(self.numer))
    else:
      print("Błąd! Popraw numer telefonu! Wpisano: {}".format(podany_numer))

  def wojewodztwo(self):
    for miasto, kierunkowy in self.slownik_kierunkowe.items(): #obsługujemy słownik
      if str(kierunkowy) == self.numer[:2]: #[:2] - pierwsze dwie cyfry numeru, ale z racji że numer to string, to trzeba było "zrzutować" kierunkowy na string
        print("Numer: {}, jeżeli jest to stacjonarny, to znajduje się w okolicy miasta: {}".format(self.numer,miasto))
        #Problem by rozróżnić np. 712 123 123 (podany bez spacji oczywiście) a 71 123 12 12 (także bez spacji) - pierwszy komórka zaczyna się na 71, drugi stacjonarny Wrocław
        #Pewnie możnaby się bawić w regex ale byłoby dużo przypadków do rozpisania

  def __repr__(self): #"podmienia" print
    return " ".join(map(lambda x : self.slownik_literuj[x], str(self.numer))) #zwróć " " i połącz (wyjaśnienie nawiasu poniżej) 
    # map - wykonanie funkcji (lambda...) dla każdego elementu str(self.numer)
    # lambda dla argumentu x zwróć słownik[x] (wartość - czyli słownie cyfrę), gdzie x to cyfra z str(self.numer)

#######################################################################################################

# Przykłady działania (& debugging)
numerkom = NumerTelefonu("737491274") #komórkowy
numersta = NumerTelefonu("426877868") #stacjonarny
numerzly = NumerTelefonu("7374912744") #zły (za długi) 
numerzly2 = NumerTelefonu("73749127.") #zły (z kropką zamiast cyfry)

numerkom.wojewodztwo()
numersta.wojewodztwo()

print(numerkom)

Podano poprawny numer: 737491274
Podano poprawny numer: 426877868
Błąd! Popraw numer telefonu! Wpisano: 7374912744
Błąd! Popraw numer telefonu! Wpisano: 73749127.
Numer: 426877868, jeżeli jest to stacjonarny, to znajduje się w okolicy miasta: Łódź
siedem trzy siedem cztery dziewięć jeden dwa siedem cztery
